import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./_component/Provider/Provider";
// import { ArrowBigUpIcon } from "lucide-react";
import ScrollToTopButton from "./_component/ScrollToTop/ScrollToTopButton";
// import WishListContextProvider from "./_component/Context/WishListContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Provider>{children}</Provider>
       <ScrollToTopButton/>
      </body>
    </html>
  );
}
